Fix #393: Improve the documentation structure
wultra/powerauth-crypto pull request #394
Opened 2022-01-03 20:12 UTC by petrdvorak

2022-01-05 11:53 UTC, hvge requested changes

2023-04-18 19:12 UTC, petrdvorak commented on docs/Activation-via-Activation-Code.md
> +- **PowerAuth Server** - A server application hidden deep in secure infrastructure, stores activation records, or verifies the request signatures. This application provides services for Intermediate
OK

2023-04-18 20:03 UTC, petrdvorak commented on docs/Activation.md
> +- [Activation via Custom Credentials](#activation-via-custom-credentials)
Fixed

2023-04-18 20:06 UTC, petrdvorak commented
I think this is good enough as the first rework of the structure. We can always adjust the documentation and add chapters, but I recommend merging what we have now.

2023-04-20 08:59 UTC, hvge approved these changes
Looks OK, I just found out that one image is a bit downgraded in resolution.

2023-08-21 14:39 UTC, merged