Fix #640: Add documentation for temporary keys
wultra/powerauth-crypto pull request #641
Opened 2024-09-06 17:45 UTC by petrdvorak

2024-09-09 18:39 UTC, hvge requested changes
I think we should also update a [End-To-End-Encryption](https://developers.wultra.com/components/powerauth-crypto/1.8.x/documentation/End-To-End-Encryption) section. There's still information that ECDH is computed with static keys. Also there's missing information about `temporaryKeyId` attribute in the payload.

2024-09-11 07:38 UTC, hvge requested changes
Just one small fix and it would be OK.

2024-09-11 07:38 UTC, hvge commented on docs/End-To-End-Encryption.md
> +- `KEY_ENC_PUB` is a [temporary key](./Temporary-Encryption-Keys.md) with given `TEMP_KEY_ID` identifier fetched from the server associated with a specific application version and activation, and sig
Signed with `KEY_SERVER_PRIVATE`.

2024-09-11 12:09 UTC, petrdvorak commented on docs/End-To-End-Encryption.md
> +- `KEY_ENC_PUB` is a [temporary key](./Temporary-Encryption-Keys.md) with given `TEMP_KEY_ID` identifier fetched from the server associated with a specific application version and activation, and sig
Thank you!

2024-09-11 12:47 UTC, merged